// Source data for the QA test-cases dashboard (app/test-cases), seeded into
// the DB by scripts/seed-test-cases.ts. Pulled from the Miro board — see
// docs/test-plan.md for the human-readable version of the same 81 cases.
//
// `automatable: true` is set ONLY for cases verified against this app's
// actual implementation and wired up in lib/test-runner/registry.ts. Most of
// the 81 test something this app doesn't implement as literally described
// (live/websocket updates, per-role permissions, document versioning, a
// dynamically-editable shared phrase library, duplicate-case detection,
// multi-day deadline waits, concurrent sessions) — those are manual-only
// regardless of how "automatable" the scenario sounds in the abstract.

export type TestCaseType = 'HAPPY' | 'NEGATIVE' | 'EDGE'

export interface TestCaseSeed {
  tcId: string
  section: string
  userStory: string
  type: TestCaseType
  scenario: string
  expected: string
  automatable: boolean
}

export const TEST_CASES: TestCaseSeed[] = [
  // 01 · Determine Jurisdiction and Authority
  { tcId: 'TC-01-01', section: '01 Determine Jurisdiction and Authority', userStory: 'US-01 Auto-detect applicable regime at intake', type: 'HAPPY', scenario: 'New case created. Requester has a confirmed UK location on file.', expected: 'GDPR (UK) identified and displayed before the draft field is available.', automatable: true },
  { tcId: 'TC-01-02', section: '01 Determine Jurisdiction and Authority', userStory: 'US-01 Auto-detect applicable regime at intake', type: 'NEGATIVE', scenario: 'Requester email uses GDPR language but confirmed location is California, USA.', expected: 'System flags a conflict and prompts counsellor to confirm the correct regime before proceeding.', automatable: false },
  { tcId: 'TC-01-03', section: '01 Determine Jurisdiction and Authority', userStory: 'US-01 Auto-detect applicable regime at intake', type: 'EDGE', scenario: 'Requester location is not on file. No contract linked to the account.', expected: 'System flags that regime cannot be auto-detected and prompts manual confirmation. Draft field remains locked.', automatable: false },
  { tcId: 'TC-02-01', section: '01 Determine Jurisdiction and Authority', userStory: 'US-02 Surface contract file and prior cases at intake', type: 'HAPPY', scenario: 'Case created. Requester account has a linked contract file and a current data flow note.', expected: 'Contract file, data flow note, and three closest prior cases appear in sidebar without any manual search.', automatable: false },
  { tcId: 'TC-02-02', section: '01 Determine Jurisdiction and Authority', userStory: 'US-02 Surface contract file and prior cases at intake', type: 'NEGATIVE', scenario: 'Case created. No contract file is linked to the requester account.', expected: 'System flags missing contract and prompts counsellor to attach one before proceeding to draft.', automatable: true },
  { tcId: 'TC-02-03', section: '01 Determine Jurisdiction and Authority', userStory: 'US-02 Surface contract file and prior cases at intake', type: 'EDGE', scenario: 'Case created. Contract file exists but data flow note is more than 12 months old.', expected: 'Data flow note surfaced with a warning that it is over 12 months old.', automatable: false },
  { tcId: 'TC-03-01', section: '01 Determine Jurisdiction and Authority', userStory: 'US-03 Auto-route to correct authority on regime confirmation', type: 'HAPPY', scenario: 'Regime confirmed as GDPR (Germany). Case ready for escalation.', expected: 'BfDI pre-filled as authority. Current complaints URL and maximum fine displayed.', automatable: true },
  { tcId: 'TC-03-02', section: '01 Determine Jurisdiction and Authority', userStory: 'US-03 Auto-route to correct authority on regime confirmation', type: 'NEGATIVE', scenario: 'Regime confirmed as GDPR (Germany). Authority URL in routing table is outdated.', expected: 'System flags that authority URL may have changed and shows the updated source.', automatable: false },
  { tcId: 'TC-03-03', section: '01 Determine Jurisdiction and Authority', userStory: 'US-03 Auto-route to correct authority on regime confirmation', type: 'EDGE', scenario: 'Regime confirmed but jurisdiction maps to a federated authority structure with multiple possible bodies.', expected: 'System presents the most likely authority and prompts counsellor to confirm. All valid options listed.', automatable: false },
  { tcId: 'TC-04-01', section: '01 Determine Jurisdiction and Authority', userStory: 'US-04 Generate jurisdiction rationale summary', type: 'HAPPY', scenario: 'Regime and authority both confirmed on an open case.', expected: 'Summary generated showing regime, basis for determination, and authority. Attached to case with timestamp.', automatable: false },
  { tcId: 'TC-04-02', section: '01 Determine Jurisdiction and Authority', userStory: 'US-04 Generate jurisdiction rationale summary', type: 'NEGATIVE', scenario: 'Regime confirmed but authority has not yet been confirmed.', expected: 'System blocks summary generation and prompts that authority must be confirmed first.', automatable: false },
  { tcId: 'TC-04-03', section: '01 Determine Jurisdiction and Authority', userStory: 'US-04 Generate jurisdiction rationale summary', type: 'EDGE', scenario: 'Case is closed. Counsellor checks whether rationale summary was included in the evidence package.', expected: 'Rationale summary present in the evidence package automatically without a separate manual step.', automatable: false },

  // 02 · Monitor Case Pipeline
  { tcId: 'TC-05-01', section: '02 Monitor Case Pipeline', userStory: 'US-05 Queue view with stage labels and day counts', type: 'HAPPY', scenario: 'Queue contains 10 open cases at various enforcement stages.', expected: 'Every case displays a stage label and a day count since receipt. No thread opening required.', automatable: false },
  { tcId: 'TC-05-02', section: '02 Monitor Case Pipeline', userStory: 'US-05 Queue view with stage labels and day counts', type: 'NEGATIVE', scenario: 'A case has crossed its GDPR 30-day deadline. Queue is refreshed.', expected: 'Breached case is visually distinct from cases still within their window.', automatable: false },
  { tcId: 'TC-05-03', section: '02 Monitor Case Pipeline', userStory: 'US-05 Queue view with stage labels and day counts', type: 'EDGE', scenario: 'A case action is logged. Queue is open in a second browser tab.', expected: 'Stage label and day count updated without a manual refresh or page reload.', automatable: false },
  { tcId: 'TC-06-01', section: '02 Monitor Case Pipeline', userStory: 'US-06 Per-regime deadline clock', type: 'HAPPY', scenario: 'New GDPR case created. Received date confirmed as Day 1.', expected: 'Case flagged as approaching on Day 25 and breached on Day 30.', automatable: false },
  { tcId: 'TC-06-02', section: '02 Monitor Case Pipeline', userStory: 'US-06 Per-regime deadline clock', type: 'NEGATIVE', scenario: 'CCPA case created with an incorrect received date. Counsellor corrects it.', expected: 'Clock recalculates from the corrected date. Flags updated to reflect corrected timeline.', automatable: false },
  { tcId: 'TC-06-03', section: '02 Monitor Case Pipeline', userStory: 'US-06 Per-regime deadline clock', type: 'EDGE', scenario: 'Case created in a jurisdiction with a local data law not yet in the routing table.', expected: 'System flags unknown regime and prompts counsellor to enter the applicable deadline manually.', automatable: false },
  { tcId: 'TC-07-01', section: '02 Monitor Case Pipeline', userStory: 'US-07 Automatic status update on logged action', type: 'HAPPY', scenario: 'Case in Awaiting identity verification. Counsellor sends a confirmation request.', expected: 'Case status updates automatically to Pending internal confirmation. No manual update required.', automatable: true },
  { tcId: 'TC-07-02', section: '02 Monitor Case Pipeline', userStory: 'US-07 Automatic status update on logged action', type: 'NEGATIVE', scenario: 'Counsellor sends a reply to the requester. Case is in drafting stage.', expected: 'Status updates to Reply sent. Case does not move to Closed — closure requires the evidence checklist.', automatable: false },
  { tcId: 'TC-07-03', section: '02 Monitor Case Pipeline', userStory: 'US-07 Automatic status update on logged action', type: 'EDGE', scenario: 'Two counsellors log actions on the same case simultaneously.', expected: 'Status reflects the most recent action. Both actions appear in case history with separate timestamps.', automatable: false },
  { tcId: 'TC-08-01', section: '02 Monitor Case Pipeline', userStory: 'US-08 Deadline risk indicator', type: 'HAPPY', scenario: 'GDPR case. Day 25 reached — 5 days remaining in the 30-day window.', expected: 'Warning indicator appears on the case in queue view. Visible without opening the thread.', automatable: true },
  { tcId: 'TC-08-02', section: '02 Monitor Case Pipeline', userStory: 'US-08 Deadline risk indicator', type: 'NEGATIVE', scenario: 'GDPR case. Day 31 reached. Requester has not yet sent a follow-up.', expected: 'Breach indicator appears and in-app notification sent. Indicator timestamp earlier than any requester follow-up.', automatable: false },
  { tcId: 'TC-08-03', section: '02 Monitor Case Pipeline', userStory: 'US-08 Deadline risk indicator', type: 'EDGE', scenario: 'Case on Day 28 with 2 days remaining. Internal confirmation is outstanding.', expected: 'Warning indicator shows. System also surfaces the outstanding confirmation request with a link.', automatable: false },

  // 03 · Qualify Incoming Cases
  { tcId: 'TC-09-01', section: '03 Qualify Incoming Cases', userStory: 'US-09 Pre-classify incoming emails before reading', type: 'HAPPY', scenario: 'New deletion request email arrives from a UK-based requester.', expected: 'Email labelled before opened: Type = Deletion, Jurisdiction = UK GDPR, Urgency = Standard, Identity = Unconfirmed.', automatable: false },
  { tcId: 'TC-09-02', section: '03 Qualify Incoming Cases', userStory: 'US-09 Pre-classify incoming emails before reading', type: 'NEGATIVE', scenario: 'Email arrives that is a general complaint, not a formal deletion or access request.', expected: 'Email classified as Type = Complaint, not Deletion or Access.', automatable: false },
  { tcId: 'TC-09-03', section: '03 Qualify Incoming Cases', userStory: 'US-09 Pre-classify incoming emails before reading', type: 'EDGE', scenario: 'Counsellor disagrees with the system classification and overrides it.', expected: 'Classification updated. Override logged with counsellor name and timestamp. Override fed back into detection model.', automatable: false },
  { tcId: 'TC-10-01', section: '03 Qualify Incoming Cases', userStory: 'US-10 Auto-create case record from classified email', type: 'HAPPY', scenario: 'Email classified as a deletion request. Regime confirmed as GDPR.', expected: 'Case record shows received date, type, owner, and deadline — all pre-filled without manual entry.', automatable: false },
  { tcId: 'TC-10-02', section: '03 Qualify Incoming Cases', userStory: 'US-10 Auto-create case record from classified email', type: 'NEGATIVE', scenario: 'Case record created. Counsellor disputes the pre-filled request type.', expected: 'Type field is editable. Change saved. Field shows who changed it and when alongside the original value.', automatable: false },
  { tcId: 'TC-10-03', section: '03 Qualify Incoming Cases', userStory: 'US-10 Auto-create case record from classified email', type: 'EDGE', scenario: 'Case record created. Counsellor checks the tracking queue immediately after.', expected: 'New case appears in queue without any manual refresh or sheet entry.', automatable: false },
  { tcId: 'TC-11-01', section: '03 Qualify Incoming Cases', userStory: 'US-11 Detect and flag holding replies', type: 'HAPPY', scenario: 'Open deletion case. Third-party replies: "Thank you for your message. We are looking into this and will come back shortly."', expected: 'Reply flagged as non-substantive. Case remains open. Deadline clock continues. Status unchanged.', automatable: false },
  { tcId: 'TC-11-02', section: '03 Qualify Incoming Cases', userStory: 'US-11 Detect and flag holding replies', type: 'NEGATIVE', scenario: 'Third-party replies with a substantive response confirming deletion of specific systems with a date.', expected: 'Reply not flagged as holding. Case status updates to reflect substantive response received.', automatable: false },
  { tcId: 'TC-11-03', section: '03 Qualify Incoming Cases', userStory: 'US-11 Detect and flag holding replies', type: 'EDGE', scenario: 'System flags a reply as holding. Counsellor believes it is actually substantive.', expected: 'Flag cleared. Case status updates. Override logged with counsellor name, timestamp, and reason.', automatable: false },
  { tcId: 'TC-12-01', section: '03 Qualify Incoming Cases', userStory: 'US-12 Detect duplicate cases from the same request', type: 'HAPPY', scenario: 'Deletion request from requester X already open as Case 001. Same requester sends an identical request 3 days later.', expected: 'System flags potential duplicate before a new case is created. Links to existing Case 001.', automatable: false },
  { tcId: 'TC-12-02', section: '03 Qualify Incoming Cases', userStory: 'US-12 Detect duplicate cases from the same request', type: 'NEGATIVE', scenario: 'Two emails from the same requester — one deletion request, one access request.', expected: 'System does not flag these as duplicates. Both cases created independently.', automatable: false },
  { tcId: 'TC-12-03', section: '03 Qualify Incoming Cases', userStory: 'US-12 Detect duplicate cases from the same request', type: 'EDGE', scenario: 'Counsellor merges a duplicate email into an existing case. Both had different received timestamps.', expected: 'Both timestamps retained. Earliest used for deadline clock. Duplicate marked as merged, not deleted.', automatable: false },

  // 04 · Draft with Compliance Checks
  { tcId: 'TC-13-01', section: '04 Draft with Compliance Checks', userStory: 'US-13 Shared snippet library at drafting start', type: 'HAPPY', scenario: 'Case in drafting. Regime GDPR. Request type deletion.', expected: 'Three closest prior approved GDPR deletion replies shown with reuse safety indicators and source links.', automatable: false },
  { tcId: 'TC-13-02', section: '04 Draft with Compliance Checks', userStory: 'US-13 Shared snippet library at drafting start', type: 'NEGATIVE', scenario: 'Case in drafting. No prior approved replies exist for this jurisdiction and request type.', expected: 'Closest available reply shown with a note that jurisdiction or type differs.', automatable: false },
  { tcId: 'TC-13-03', section: '04 Draft with Compliance Checks', userStory: 'US-13 Shared snippet library at drafting start', type: 'EDGE', scenario: 'Counsellor inserts a prior reply. The source case is later flagged as incorrectly closed.', expected: 'System flags the inserted text with a warning that the source case has been flagged.', automatable: false },
  { tcId: 'TC-14-01', section: '04 Draft with Compliance Checks', userStory: 'US-14 In-context provision currency check', type: 'HAPPY', scenario: 'Counsellor references Article 17 GDPR in the draft.', expected: 'Current text of Article 17 shown from EUR-Lex with retrieval date.', automatable: false },
  { tcId: 'TC-14-02', section: '04 Draft with Compliance Checks', userStory: 'US-14 In-context provision currency check', type: 'NEGATIVE', scenario: 'Counsellor references a provision that was amended 2 months ago.', expected: 'Flag appears that provision was updated since it was last used — please review before sending.', automatable: false },
  { tcId: 'TC-14-03', section: '04 Draft with Compliance Checks', userStory: 'US-14 In-context provision currency check', type: 'EDGE', scenario: 'Counsellor copies a provision citation from a legal blog and pastes it into the draft.', expected: 'System replaces blog URL with official source URL and notes the substitution.', automatable: false },
  { tcId: 'TC-15-01', section: '04 Draft with Compliance Checks', userStory: 'US-15 Broad language and verb flag before send', type: 'HAPPY', scenario: 'Counsellor drafts a reply containing "all data has been deleted."', expected: 'Inline flag with reason and suggested replacement. Send action not yet available.', automatable: true },
  { tcId: 'TC-15-02', section: '04 Draft with Compliance Checks', userStory: 'US-15 Broad language and verb flag before send', type: 'NEGATIVE', scenario: 'Draft contains the word "confirm" in the sentence "We confirm receipt of your request."', expected: 'Confirm highlighted. Counsellor must confirm the usage or replace it before send becomes available.', automatable: false },
  { tcId: 'TC-15-03', section: '04 Draft with Compliance Checks', userStory: 'US-15 Broad language and verb flag before send', type: 'EDGE', scenario: 'Counsellor accepts a suggested replacement for a flagged phrase. Replacement is novel and not yet in the library.', expected: 'Replacement added to the shared phrase library automatically.', automatable: false },
  { tcId: 'TC-16-01', section: '04 Draft with Compliance Checks', userStory: 'US-16 Plain-text drafting gate', type: 'HAPPY', scenario: 'Draft reply completed. Counsellor requests to move to send-ready format.', expected: 'Reply presented in plain-text. Confirmation logged with name and timestamp. Reply moves to send-ready.', automatable: false },
  { tcId: 'TC-16-02', section: '04 Draft with Compliance Checks', userStory: 'US-16 Plain-text drafting gate', type: 'NEGATIVE', scenario: 'Draft reply completed. Counsellor attempts to send directly without completing the plain-text review.', expected: 'Send blocked. System returns to plain-text review step with a note.', automatable: false },
  { tcId: 'TC-16-03', section: '04 Draft with Compliance Checks', userStory: 'US-16 Plain-text drafting gate', type: 'EDGE', scenario: 'Counsellor A confirms plain-text review. Counsellor B makes an edit after confirmation.', expected: 'Post-review edit triggers a new review requirement. Send blocked until updated version is reviewed.', automatable: false },
  { tcId: 'TC-17-01', section: '04 Draft with Compliance Checks', userStory: 'US-17 Team-wide phrase library', type: 'HAPPY', scenario: 'A sent reply received a compliance follow-up citing "all personal data has been removed" as unclear.', expected: 'Phrase added to shared library. Future drafts by any counsellor trigger the flag with the note visible.', automatable: false },
  { tcId: 'TC-17-02', section: '04 Draft with Compliance Checks', userStory: 'US-17 Team-wide phrase library', type: 'NEGATIVE', scenario: 'A counsellor types "all personal information has been erased" — a variant of the flagged phrase.', expected: 'Flag fires for the variant with the library note and reference to the case that prompted it.', automatable: false },
  { tcId: 'TC-17-03', section: '04 Draft with Compliance Checks', userStory: 'US-17 Team-wide phrase library', type: 'EDGE', scenario: 'Team lead removes an entry from the shared phrase library. A counsellor has that phrase flagged in an active draft.', expected: 'Flag clears from the active draft immediately. Counsellor notified that a phrase flag was removed.', automatable: false },

  // 05 · Validate Before Filing
  { tcId: 'TC-18-01', section: '05 Validate Before Filing', userStory: 'US-18 Structured confirmation form for internal teams', type: 'HAPPY', scenario: "Internal team member logged in with active case. Opens case, clicks 'Confirm for Filing', fills required fields, submits.", expected: 'Form validates all fields, confirmation recorded, timestamp logged.', automatable: false },
  { tcId: 'TC-18-02', section: '05 Validate Before Filing', userStory: 'US-18 Structured confirmation form for internal teams', type: 'NEGATIVE', scenario: 'User attempts submission with missing required fields.', expected: 'Submission blocked; inline errors highlight each missing field.', automatable: false },
  { tcId: 'TC-18-03', section: '05 Validate Before Filing', userStory: 'US-18 Structured confirmation form for internal teams', type: 'EDGE', scenario: 'Two team members open the same case confirmation form concurrently and submit near-simultaneously.', expected: 'First submission accepted; second sees conflict warning with latest state.', automatable: false },
  { tcId: 'TC-19-01', section: '05 Validate Before Filing', userStory: 'US-19 Auto-assembled evidence record with completeness gate', type: 'HAPPY', scenario: 'Case has all required evidence documents uploaded.', expected: 'Complete evidence record generated; completeness gate passes.', automatable: false },
  { tcId: 'TC-19-02', section: '05 Validate Before Filing', userStory: 'US-19 Auto-assembled evidence record with completeness gate', type: 'NEGATIVE', scenario: 'Case is missing one or more required evidence items.', expected: 'Assembly blocked; gate returns list of missing items.', automatable: false },
  { tcId: 'TC-19-03', section: '05 Validate Before Filing', userStory: 'US-19 Auto-assembled evidence record with completeness gate', type: 'EDGE', scenario: 'Evidence document is present but corrupted or unreadable.', expected: 'Corrupt file flagged; gate blocks with actionable error.', automatable: false },
  { tcId: 'TC-20-01', section: '05 Validate Before Filing', userStory: 'US-20 Visible sourcing for generated draft sentences', type: 'HAPPY', scenario: 'Draft generated from case evidence with sources indexed.', expected: 'Source citation shown with document reference and page.', automatable: false },
  { tcId: 'TC-20-02', section: '05 Validate Before Filing', userStory: 'US-20 Visible sourcing for generated draft sentences', type: 'NEGATIVE', scenario: 'Generated sentence has no verifiable source.', expected: 'Sentence flagged as unsourced; blocks filing until resolved.', automatable: false },
  { tcId: 'TC-20-03', section: '05 Validate Before Filing', userStory: 'US-20 Visible sourcing for generated draft sentences', type: 'EDGE', scenario: 'Sentence draws from multiple conflicting sources.', expected: 'All sources listed; conflict highlighted for reviewer.', automatable: false },
  { tcId: 'TC-21-01', section: '05 Validate Before Filing', userStory: 'US-21 Case closure conditional on evidence checklist', type: 'HAPPY', scenario: 'All evidence checklist items marked complete.', expected: 'Case closes successfully; closure timestamp recorded.', automatable: true },
  { tcId: 'TC-21-02', section: '05 Validate Before Filing', userStory: 'US-21 Case closure conditional on evidence checklist', type: 'NEGATIVE', scenario: 'One or more checklist items still incomplete.', expected: 'Closure blocked; incomplete items listed for user.', automatable: true },
  { tcId: 'TC-21-03', section: '05 Validate Before Filing', userStory: 'US-21 Case closure conditional on evidence checklist', type: 'EDGE', scenario: 'Checklist item marked complete but underlying evidence later revoked.', expected: 'Closure blocked; stale checklist item re-opened automatically.', automatable: false },

  // 06 · Maintain Shared Visibility
  { tcId: 'TC-22-01', section: '06 Maintain Shared Visibility', userStory: 'US-22 Shared live case view', type: 'HAPPY', scenario: 'Multi-person case with counsellor, PM, and compliance lead. Case is Pending internal confirmation. Each stakeholder opens the case record independently.', expected: 'All three see current status, last action with timestamp, outstanding actions, and step owner. No message needed.', automatable: false },
  { tcId: 'TC-22-02', section: '06 Maintain Shared Visibility', userStory: 'US-22 Shared live case view', type: 'NEGATIVE', scenario: 'Compliance lead has view-only access. They attempt to update the case status.', expected: 'Edit action blocked for view-only user. All status information remains visible.', automatable: false },
  { tcId: 'TC-22-03', section: '06 Maintain Shared Visibility', userStory: 'US-22 Shared live case view', type: 'EDGE', scenario: 'Case status changes while a stakeholder is actively viewing the shared case view.', expected: 'Shared view updates in real time. Status change visible without a refresh.', automatable: false },
  { tcId: 'TC-23-01', section: '06 Maintain Shared Visibility', userStory: 'US-23 Per-case status indicator with stage breakdown', type: 'HAPPY', scenario: 'Queue contains cases in all four states: In progress, Waiting on confirmation, Deadline approaching, Complete.', expected: 'Each case shows one of the four states. Waiting on confirmation names the step owner. Deadline approaching shows days remaining.', automatable: false },
  { tcId: 'TC-23-02', section: '06 Maintain Shared Visibility', userStory: 'US-23 Per-case status indicator with stage breakdown', type: 'NEGATIVE', scenario: 'Counsellor filters case list by Waiting on confirmation.', expected: 'Only cases with Waiting on confirmation status shown. All others hidden. Filter can be cleared.', automatable: false },
  { tcId: 'TC-23-03', section: '06 Maintain Shared Visibility', userStory: 'US-23 Per-case status indicator with stage breakdown', type: 'EDGE', scenario: 'Case moves from Deadline approaching to Complete in the same queue refresh cycle.', expected: 'Status updates directly to Complete. Status history retains both entries with timestamps.', automatable: false },
  { tcId: 'TC-24-01', section: '06 Maintain Shared Visibility', userStory: 'US-24 Full edit history with author and timestamp', type: 'HAPPY', scenario: 'Three counsellors edited a draft — A wrote original, B changed a verb, C added a sentence.', expected: 'All three edits recorded with author, timestamp, original text, and replacement text.', automatable: false },
  { tcId: 'TC-24-02', section: '06 Maintain Shared Visibility', userStory: 'US-24 Full edit history with author and timestamp', type: 'NEGATIVE', scenario: 'Counsellor wants to see only the edits made by Counsellor B.', expected: 'Only B’s edits shown. All other entries hidden. Filter can be cleared.', automatable: false },
  { tcId: 'TC-24-03', section: '06 Maintain Shared Visibility', userStory: 'US-24 Full edit history with author and timestamp', type: 'EDGE', scenario: 'Counsellor A and Counsellor B edit the same sentence simultaneously.', expected: 'Both edits recorded separately. A conflict flag prompts the counsellor to review which version to keep.', automatable: false },
  { tcId: 'TC-25-01', section: '06 Maintain Shared Visibility', userStory: 'US-25 Approval gate before filing', type: 'HAPPY', scenario: 'Draft reply ready for filing. Named reviewer is the senior legal counsel. Reviewer approves.', expected: 'Approval confirmed. Version locked. Filing proceeds. Locked version and approval timestamp recorded.', automatable: true },
  { tcId: 'TC-25-02', section: '06 Maintain Shared Visibility', userStory: 'US-25 Approval gate before filing', type: 'NEGATIVE', scenario: 'Approved version exists. A counsellor makes an edit after approval and attempts to file.', expected: 'Filing blocked. Message shown that current version differs from approved and a new approval is required.', automatable: true },
  { tcId: 'TC-25-03', section: '06 Maintain Shared Visibility', userStory: 'US-25 Approval gate before filing', type: 'EDGE', scenario: 'Named reviewer is unavailable. Filing is time-sensitive — deadline is today.', expected: 'System offers an escalation path to request approval from an authorised backup reviewer.', automatable: false },
  { tcId: 'TC-26-01', section: '06 Maintain Shared Visibility', userStory: 'US-26 Version control replacing filename convention', type: 'HAPPY', scenario: 'Draft exists. Counsellor makes an edit.', expected: 'New version created automatically with version number, author name, timestamp, and one-line change summary.', automatable: false },
  { tcId: 'TC-26-02', section: '06 Maintain Shared Visibility', userStory: 'US-26 Version control replacing filename convention', type: 'NEGATIVE', scenario: 'Current version is v5. Counsellor wants to restore v3.', expected: 'Restoration creates v6 with a note that it was restored from v3. v1 through v5 remain in history unchanged.', automatable: false },
  { tcId: 'TC-26-03', section: '06 Maintain Shared Visibility', userStory: 'US-26 Version control replacing filename convention', type: 'EDGE', scenario: 'Two counsellors save edits simultaneously to different parts of the draft.', expected: 'Two new versions created in sequence. Both edits recorded. A rapid-succession note prompts a review.', automatable: false },
  { tcId: 'TC-27-01', section: '06 Maintain Shared Visibility', userStory: 'US-27 Shared coordination log', type: 'HAPPY', scenario: 'Multi-person case closed after a coordination failure where the PM sent a status message because the shared view was not checked.', expected: 'Coordination issue and resolution saved to shared log and linked to this case type.', automatable: false },
  { tcId: 'TC-27-02', section: '06 Maintain Shared Visibility', userStory: 'US-27 Shared coordination log', type: 'NEGATIVE', scenario: 'A new multi-person deletion case is opened. The coordination log has 2 relevant prior entries for deletion cases.', expected: 'Two most relevant log entries shown as a prompt at case start.', automatable: false },
  { tcId: 'TC-27-03', section: '06 Maintain Shared Visibility', userStory: 'US-27 Shared coordination log', type: 'EDGE', scenario: 'Team lead marks a coordination log entry as resolved at process level after a workflow change.', expected: 'Resolved entry no longer appears as a prompt for new cases. It remains in the log as archived but not surfaced as active.', automatable: false },
]
